Systembankunipim/Systembankunipim/Controllers/RelatorioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Systembankunipim.Data;

namespace Systembankunipim.Controllers
{
    public class RelatorioController : Controller
    {
        private readonly SYSTEMBANKUNIPIMContext _context;

        public RelatorioController(SYSTEMBANKUNIPIMContext context)
        {
            _context = context;
        }

        public IActionResult Index()
        {
            return View();
        }
    }
}

Systembankunipim/Systembankunipim/Controllers/TbCarteirasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Systembankunipim.Data;

namespace Systembankunipim.Controllers
{
    public class TbCarteirasController : Controller
    {
        private readonly SYSTEMBANKUNIPIMContext _context;

        public TbCarteirasController(SYSTEMBANKUNIPIMContext context)
        {
            _context = context;
        }

        // GET: TbCarteiras
        public async Task<IActionResult> Index()
        {
            var sYSTEMBANKUNIPIMContext = _context.TbCarteira.Include(t => t.IdClienteNavigation);
            return View(await sYSTEMBANKUNIPIMContext.ToListAsync());
        }

        // GET: TbCarteiras/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCarteira = await _context.TbCarteira
                .Include(t => t.IdClienteNavigation)
                .FirstOrDefaultAsync(m => m.IdCarteira == id);
            if (tbCarteira == null)
            {
                return NotFound();
            }

            return View(tbCarteira);
        }

        // GET: TbCarteiras/Create
        public IActionResult Create()
        {
            ViewData["IdCliente"] = new SelectList(_context.TbCliente, "IdCliente", "Email");
            return View();
        }

        // POST: TbCarteiras/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCarteira,IdCliente,SaldoCarteira,UltimoDeposito,UltimoSaque,DataUltimaTransacao")] TbCarteira tbCarteira)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbCarteira);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.TbCliente, "IdCliente", "Email", tbCarteira.IdCliente);
            return View(tbCarteira);
        }

        // GET: TbCarteiras/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCarteira = await _context.TbCarteira.FindAsync(id);
            if (tbCarteira == null)
            {
                return NotFound();
            }
            ViewData["IdCliente"] = new SelectList(_context.TbCliente, "IdCliente", "Email", tbCarteira.IdCliente);
            return View(tbCarteira);
        }

        // POST: TbCarteiras/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCarteira,IdCliente,SaldoCarteira,UltimoDeposito,UltimoSaque,DataUltimaTransacao")] TbCarteira tbCarteira)
        {
            if (id != tbCarteira.IdCarteira)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbCarteira);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbCarteiraExists(tbCarteira.IdCarteira))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCliente"] = new SelectList(_context.TbCliente, "IdCliente", "Email", tbCarteira.IdCliente);
            return View(tbCarteira);
        }

        // GET: TbCarteiras/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCarteira = await _context.TbCarteira
                .Include(t => t.IdClienteNavigation)
                .FirstOrDefaultAsync(m => m.IdCarteira == id);
            if (tbCarteira == null)
            {
                return NotFound();
            }

            return View(tbCarteira);
        }

        // POST: TbCarteiras/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbCarteira = await _context.TbCarteira.FindAsync(id);
            _context.TbCarteira.Remove(tbCarteira);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbCarteiraExists(int id)
        {
            return _context.TbCarteira.Any(e => e.IdCarteira == id);
        }
    }
}

Systembankunipim/Systembankunipim/Controllers/TbClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Systembankunipim.Bibliotecas.Session;
using Systembankunipim.Data;

// O Controller precisa ter o mesmo nome da pasta da View
// Eu fiz a parte de login separada da controlleer cliente 
namespace Systembankunipim.Controllers
{
    public class TbClientesController : Controller
    {
        private readonly SYSTEMBANKUNIPIMContext _context;
        private Session _session;
        private IHttpContextAccessor _http;

        public TbClientesController(SYSTEMBANKUNIPIMContext context, Session session, IHttpContextAccessor http)
        {
            _context = context;
            _session = session;
            _http = http;
        }

        public IActionResult Index()
        {
            string getCliente = _session.Consultar("Login"); // Verifica se a sessão existe
            if (getCliente != null) // Se resultado não for null, faça:
            {
                TbCliente cliente = JsonConvert.DeserializeObject<TbCliente>(getCliente); //Descerializa o objeto
                TbCliente view = _context.TbCliente.Find(cliente.IdCliente); // Pega os dados do cliente no banco e armazena na variável como objeto
                return View(view); // Retorna o objeto para a View
            }
            else // Se for null, redireciona para página de login
            {
                return RedirectToAction("Index","Login");
            }
        }

        [HttpGet]
        public IActionResult Cliente(int id)
        {
            return View();
        }

        // GET: TbClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCliente = await _context.TbCliente
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (tbCliente == null)
            {
                return NotFound();
            }

            return View(tbCliente);
        }

        // GET: TbClientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TbClientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCliente,Nome,Cpf,Cnpj,DtNasc,Telefone,Email,Senha")] TbCliente tbCliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbCliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tbCliente);
        }

        // GET: TbClientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCliente = await _context.TbCliente.FindAsync(id);
            if (tbCliente == null)
            {
                return NotFound();
            }
            return View(tbCliente);
        }

        // POST: TbClientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCliente,Nome,Cpf,Cnpj,DtNasc,Telefone,Email,Senha")] TbCliente tbCliente)
        {
            if (id != tbCliente.IdCliente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbCliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbClienteExists(tbCliente.IdCliente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tbCliente);
        }

        // GET: TbClientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCliente = await _context.TbCliente
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (tbCliente == null)
            {
                return NotFound();
            }

            return View(tbCliente);
        }

        // POST: TbClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbCliente = await _context.TbCliente.FindAsync(id);
            _context.TbCliente.Remove(tbCliente);
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbClienteExists(int id)
        {
            return _context.TbCliente.Any(e => e.IdCliente == id);
        }
    }
}

Systembankunipim/Systembankunipim/Controllers/TbTransacoesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Systembankunipim.Data;

namespace Systembankunipim.Controllers
{
    public class TbTransacoesController : Controller
    {
        private readonly SYSTEMBANKUNIPIMContext _context;

        public TbTransacoesController(SYSTEMBANKUNIPIMContext context)
        {
            _context = context;
        }
       
        // GET: TbTransacoes
        public async Task<IActionResult> Index()
        {
            var transacao = _context.TbTransacao.Include(t => t.IdCarteiraNavigation).Include(t => t.IdTipoTransacaoNavigation);
            return View(await transacao.ToListAsync());
        }

        // GET: TbTransacoes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbTransacao = await _context.TbTransacao
                .Include(t => t.IdCarteiraNavigation)
                .Include(t => t.IdTipoTransacaoNavigation)
                .FirstOrDefaultAsync(m => m.IdTransacao == id);
            if (tbTransacao == null)
            {
                return NotFound();
            }

            return View(tbTransacao);
        }

        // GET: TbTransacoes/Create
        public IActionResult Create()
        {
            ViewData["IdCarteira"] = new SelectList(_context.TbCarteira, "IdCarteira", "IdCarteira");
            ViewData["IdTipoTransacao"] = new SelectList(_context.TbTipoTransacao, "IdTipoTransacao");
            return View();
        }

        // POST: TbTransacoes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdTransacao,IdCarteira,IdTipoTransacao,ValorTransacao,CarteiraDestino,AgenciaDestino,ContaDestino")] TbTransacao tbTransacao)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbTransacao);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCarteira"] = new SelectList(_context.TbCarteira, "IdCarteira", "IdCarteira", tbTransacao.IdCarteira);
            ViewData["IdTipoTransacao"] = new SelectList(_context.TbTipoTransacao, "IdTipoTransacao", "DescricaoTransacao", tbTransacao.IdTipoTransacao);
            return View(tbTransacao);
        }

        // GET: TbTransacoes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbTransacao = await _context.TbTransacao.FindAsync(id);
            if (tbTransacao == null)
            {
                return NotFound();
            }
            ViewData["IdCarteira"] = new SelectList(_context.TbCarteira, "IdCarteira", "IdCarteira", tbTransacao.IdCarteira);
            ViewData["IdTipoTransacao"] = new SelectList(_context.TbTipoTransacao, "IdTipoTransacao", "DescricaoTransacao", tbTransacao.IdTipoTransacao);
            return View(tbTransacao);
        }

        // POST: TbTransacoes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdTransacao,IdCarteira,IdTipoTransacao,ValorTransacao,CarteiraDestino,AgenciaDestino,ContaDestino")] TbTransacao tbTransacao)
        {
            if (id != tbTransacao.IdTransacao)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbTransacao);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbTransacaoExists(tbTransacao.IdTransacao))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            ViewData["IdCarteira"] = new SelectList(_context.TbCarteira, "IdCarteira", "IdCarteira", tbTransacao.IdCarteira);
            ViewData["IdTipoTransacao"] = new SelectList(_context.TbTipoTransacao, "IdTipoTransacao", "DescricaoTransacao", tbTransacao.IdTipoTransacao);
            return View(tbTransacao);
        }

        // GET: TbTransacoes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbTransacao = await _context.TbTransacao
                .Include(t => t.IdCarteiraNavigation)
                .Include(t => t.IdTipoTransacaoNavigation)
                .FirstOrDefaultAsync(m => m.IdTransacao == id);
            if (tbTransacao == null)
            {
                return NotFound();
            }

            return View(tbTransacao);
        }

        // POST: TbTransacoes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbTransacao = await _context.TbTransacao.FindAsync(id);
            _context.TbTransacao.Remove(tbTransacao);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbTransacaoExists(int id)
        {
            return _context.TbTransacao.Any(e => e.IdTransacao == id);
        }
    }
}

Systembankunipim/Systembankunipim/Views/TbClientes/Create.cshtml
@model Systembankunipim.Data.TbCliente

@{
    ViewData["Title"] = "Novo Cadastro";
}

<h1>@ViewData["Title"]</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cnpj" class="control-label"></label>
                <input asp-for="Cnpj" class="form-control" />
                <span asp-validation-for="Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DtNasc" class="control-label"></label>
                <input asp-for="DtNasc" class="form-control" />
                <span asp-validation-for="DtNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Criar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Voltar para a lista!</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Systembankunipim/Systembankunipim/Views/TbClientes/Delete.cshtml
@model Systembankunipim.Data.TbCliente

@{
    ViewData["Title"] = "Remover Conta";
}

<h1>@ViewData["Title"]</h1>

<h4>Tem certeza que deseja remover esta conta?</h4>
<div>
    <h3>Cliente</h3>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cnpj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cnpj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DtNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DtNasc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Senha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Senha)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="IdCliente" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-primary" asp-action="Index">Voltar para lista!</a>
    </form>
</div>

Systembankunipim/Systembankunipim/Views/TbClientes/Details.cshtml
@model Systembankunipim.Data.TbCliente

@{
    ViewData["Title"] = "Detalhes";
}

<h1>@ViewData["Title"]</h1>

<div>
    <h4>Cliente</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Nome)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Nome)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cpf)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cpf)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Cnpj)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Cnpj)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DtNasc)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DtNasc)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Telefone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Telefone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
       
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Senha)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Senha)
        </dd>
    </dl>
</div>
<div>
    <a class="btn btn-primary" asp-action="Edit" asp-route-id="@Model.IdCliente">Editar</a> |
    <a class="btn btn-primary" asp-action="Index">Voltar a lista!</a>
</div>

Systembankunipim/Systembankunipim/Views/TbClientes/Edit.cshtml
@model Systembankunipim.Data.TbCliente

@{
    ViewData["Title"] = "Editar";
}

<h1>@ViewData["Title"]</h1>

<h4>Cliente</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="IdCliente" />
            <div class="form-group">
                <label asp-for="Nome" class="control-label"></label>
                <input asp-for="Nome" class="form-control" />
                <span asp-validation-for="Nome" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cpf" class="control-label"></label>
                <input asp-for="Cpf" class="form-control" />
                <span asp-validation-for="Cpf" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Cnpj" class="control-label"></label>
                <input asp-for="Cnpj" class="form-control" />
                <span asp-validation-for="Cnpj" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DtNasc" class="control-label"></label>
                <input asp-for="DtNasc" class="form-control" />
                <span asp-validation-for="DtNasc" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Telefone" class="control-label"></label>
                <input asp-for="Telefone" class="form-control" />
                <span asp-validation-for="Telefone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <label asp-for="Senha" class="control-label"></label>
                <input asp-for="Senha" class="form-control" />
                <span asp-validation-for="Senha" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Salvar" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-primary" asp-action="Index">Voltar a lista!</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Systembankunipim/Systembankunipim/Views/TbClientes/Index.cshtml
@model Systembankunipim.Data.TbCliente

@{
    ViewData["Title"] = "Cliente";
}
<hr />
<script>
    alert("Seja bem vindo!");
</script>
<div class="text-center">
    <ul class="nav justify-content-center">
        <li class="nav-item text-center">
            <a class="navbar-dark text-dark btn btn-outline-dark mr-2" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
        </li>
        <li class="nav-item">
            <a class="navbar-dark text-dark btn btn-outline-dark mr-2" asp-area="" asp-controller="TbInvestimentos" asp-action="Index">Investimento</a>
        </li>
        <li class="nav-item">
            <a class="navbar-dark text-dark btn btn-outline-dark mr-2" asp-area="" asp-controller="TbCarteiras" asp-action="Index">Carteiras</a>
        </li>
        <li class="nav-item">
            <a class="navbar-dark text-dark btn btn-outline-dark mr-2" asp-area="" asp-controller="TbTransacoes" asp-action="Index">Transações</a>
        </li>
        <li class="nav-item">
            <a class="navbar-dark text-dark btn btn-outline-dark mr-2" asp-area="" asp-controller="Relatorio" asp-action="Index">Relatorio</a>
        </li>
    </ul>
</div>
<hr />
<h1 class=" text-center display-3">Seja bem vindo!</h1>

<hr />

<div class="container">
    <div>
        <div class="col-sm">
            <div class="card" style="width: 18rem;">
                <li class="list-group list-group-flush">
                <li class="list-group-item"><img src="~/Imagens/iconfinder_avatar_1814089.png" /> <p class="font-weight-bold">@Model.Nome</p></li>
                <li class="list-group-item"><p class="font-weight-bold">@Html.DisplayNameFor(model => model.Nome) :</p> @Model.Nome<p></p> </li>
                <li class="list-group-item"><p class="font-weight-bold">@Html.DisplayNameFor(model => model.Cpf) :</p> @Model.Cpf</li>
                <li class="list-group-item"><p class="font-weight-bold">@Html.DisplayNameFor(model => model.Cnpj) :</p> @Model.Cnpj</li>
                <li class="list-group-item"><p class="font-weight-bold"> @Html.DisplayNameFor(model => model.DtNasc) :</p>  @Model.DtNasc</li>
                <li class="list-group-item"><p class="font-weight-bold">@Html.DisplayNameFor(model => model.Telefone) </p> :  @Model.Telefone</li>
                <li class="list-group-item"><p class="font-weight-bold">@Html.DisplayNameFor(model => model.Email) :</p> @Model.Email</li>
                <li class="list-group-item"><p class="font-weight-bold">@Html.DisplayNameFor(model => model.Senha) :</p> @Model.Senha</li>
                <li><a class="list-group-item btn btn-primary" asp-area="" asp-controller="Home" asp-action="Index">Sair</a></li>
            </div>
        </div>

    </div>
</div>
<div class="text-center">
    <td>
        <a class="btn btn-warning" asp-action="Edit" asp-route-id="@Model.IdCliente">Editar</a>
        <a class="btn btn-info" asp-action="Details" asp-route-id="@Model.IdCliente">Detalhes</a>
        <a class="btn btn-danger" asp-action="Delete" asp-route-id="@Model.IdCliente">Deletar</a>
    </td>
</div>