Systembankunipim/Systembankunipim/Controllers/TbClientesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Newtonsoft.Json;
using Systembankunipim.Bibliotecas.Session;
using Systembankunipim.Data;

// O Controller precisa ter o mesmo nome da pasta da View
// Eu fiz a parte de login separada da controlleer cliente 
namespace Systembankunipim.Controllers
{
    public class TbClientesController : Controller
    {
        private readonly SYSTEMBANKUNIPIMContext _context;
        private Session _session;
        private IHttpContextAccessor _http;

        public TbClientesController(SYSTEMBANKUNIPIMContext context, Session session, IHttpContextAccessor http)
        {
            _context = context;
            _session = session;
            _http = http;
        }

        public IActionResult Index()
        {
            string getCliente = _session.Consultar("Login"); // Verifica se a sessão existe
            if (getCliente != null) // Se resultado não for null, faça:
            {
                TbCliente cliente = JsonConvert.DeserializeObject<TbCliente>(getCliente); //Descerializa o objeto
                TbCliente view = _context.TbCliente.Find(cliente.IdCliente); // Pega os dados do cliente no banco e armazena na variável como objeto
                return View(view); // Retorna o objeto para a View
            }
            else // Se for null, redireciona para página de login
            {
                return RedirectToAction("Index","Login");
            }
        }

        [HttpGet]
        public IActionResult Cliente(int id)
        {
            return View();
        }

        // GET: TbClientes/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCliente = await _context.TbCliente
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (tbCliente == null)
            {
                return NotFound();
            }

            return View(tbCliente);
        }

        // GET: TbClientes/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: TbClientes/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("IdCliente,Nome,Cpf,Cnpj,DtNasc,Telefone,Email,Senha")] TbCliente tbCliente)
        {
            if (ModelState.IsValid)
            {
                _context.Add(tbCliente);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(tbCliente);
        }

        // GET: TbClientes/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCliente = await _context.TbCliente.FindAsync(id);
            if (tbCliente == null)
            {
                return NotFound();
            }
            return View(tbCliente);
        }

        // POST: TbClientes/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("IdCliente,Nome,Cpf,Cnpj,DtNasc,Telefone,Email,Senha")] TbCliente tbCliente)
        {
            if (id != tbCliente.IdCliente)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(tbCliente);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!TbClienteExists(tbCliente.IdCliente))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(tbCliente);
        }

        // GET: TbClientes/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tbCliente = await _context.TbCliente
                .FirstOrDefaultAsync(m => m.IdCliente == id);
            if (tbCliente == null)
            {
                return NotFound();
            }

            return View(tbCliente);
        }

        // POST: TbClientes/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var tbCliente = await _context.TbCliente.FindAsync(id);
            _context.TbCliente.Remove(tbCliente);
            
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool TbClienteExists(int id)
        {
            return _context.TbCliente.Any(e => e.IdCliente == id);
        }
    }
}

Systembankunipim/Systembankunipim/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - System Bank Unipim</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class=" text-center navbar navbar-expand-sm navbar-toggleable-sm navbar-light  border-bottom shadow-lg p-3 mb-5 bg-primary rounded ">
            <div class="container">
                <div class="text-center">

                    <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">System bank unipim</a>
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                </div>

                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse text-center">
                    <ul class="navbar-nav flex-grow-1 text-center 2p">
                        <li class="nav-item text-center">
                            <a class="nav-link text-white btn btn-outline-light m-2" asp-area="" asp-controller="Home" asp-action="Index">Inicio</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white btn btn-outline-light m-2" href="https://braziliex.com/?par=cf_marquee_logo">Mercado</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white btn btn-outline-light m-2" asp-area="" asp-controller="Home" asp-action="QSomos">Quem Somos!</a>
                        </li>
                    </ul>
                </div>
                <div class="float-left">
                    <a class="text-white btn btn-outline-light" asp-area="" asp-controller="Login" asp-action="Index">Login</a>
                    <a class="text-white btn btn-outline-light" asp-area="" asp-controller="TbClientes" asp-action="Create">Cadastrar</a>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">

        <div>
            <ul class="nav justify-content-center text-center font-weight">
                <li class="nav-item text-center">
                    &copy; 2020 - System Bank Unipim |
                </li>
                <li><i class="fab fa-instagram"></i></li>
                <li><i class="fab fa-linkedin"></i></li>
                <li><i class="fab fa-github"></i></li>
                <li><i class="fab fa-facebook"></i></li>
            </ul>
        </div>
    </footer>
    <script src="https://kit.fontawesome.com/bf7e05c402.js" crossorigin="anonymous"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>